### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by JimKaidyNASA** [nasa/ECI#42]
I am getting a seg fault when running my app (CNT_app) in core-linux.bin.  Any assistance in tracing this back to the origin would be appreciated.

![image](https://user-images.githubusercontent.com/52501916/66436388-ee406380-e9f4-11e9-8d51-0fa3121c4b1d.png)

**Comment by SpaceSteve121** [comment]
Jim, if you examine the traceback you'll see that the error is originating from the `sb_init()` function within ECI, specifically the `CFE_PSP_MemSet()` call [here](https://github.com/nasa/ECI/blob/master/fsw/src/eci_app.c#L359). That's initializing the command queue for your packets. 

Looking at the arguments in the traceback, its attempting to initialize 4300 bytes starting at memory address 0. The fact that its attempting to set memory address zero is the part causing the segfault (because your program shouldn't/doesn't have permission to write there). Somehow the definition of the message point is invalid.

To try to track that down, can you post (at least):
* the portion of `eci_interface.h` in which your command messages are defined 
* the header files containing the typedefs of the structures you're using for your messages

**Comment by JimKaidyNASA** [comment]
![image](https://user-images.githubusercontent.com/52501916/66486972-90a22a80-ea79-11e9-9391-5c667f7c9209.png)

The image above has the sent and received messages in eci_interface.h.  Can you tell me where the header files are that contain the typedefs for the messages?

**Comment by JimKaidyNASA** [comment]
Would this be it in platform_inc/cntECI_msgids.h:

![image](https://user-images.githubusercontent.com/52501916/66487318-1d4ce880-ea7a-11e9-80c8-a4ab6a95065c.png)

**Comment by SpaceSteve121** [comment]
If you look at the input messages that are being defined in the image you posted (ie, the elements on the MsgSend structure), you'll see the structure being instantiated is of type ECI_Msg_t. That structure type is defined [here](https://github.com/nasa/ECI/blob/master/fsw/src/eci_app.h#L50). Note that the 4th element is `qptr`, which is supposed to be a pointer to the command queue for commands and NULL for telemetry messages. 

That `qptr` is the first argument to the `CFE_PSP_MemSet` that we noted above.  In the image you posted the 4th element is `NULL` for all of your packets, which has a value of zero. So that explains why your app is attempting to set memory address zero.

The SIL will only define that 4th element to be NULL if you define the packet as a telemetry packet in Simulink. Can you confirm that's the case?

Note that the [only case the ECI attempts to setup the queue](https://github.com/nasa/ECI/blob/master/fsw/src/eci_app.c#L328) is if the message is defined with a command message ID. Based on `cntECI_msgids.h`, it looks like all of your input packets are defined with command MID's despite them being defined as telemetry messages in your model. That mismatch is what's causing your problem.

If your inputs really are command messages, then you need to update your model to reflect that. If they're really telemetry messages, then you need to define the MID's appropriately to reflect that.

**Comment by SpaceSteve121** [comment]
@BaldBeacon Please review the issue above.

What do you think about adding a check to ECI [here](https://github.com/nasa/ECI/blob/master/fsw/src/eci_app.c#L328) to catch this sort of misconfiguration? I don't think there's ever a case where that's a valid configuration, and I think you might've actually ran into this same issue before (when working with ECI, not SIL specifically).

We'd just need to check that `MsgRcv[idx].MsgStruct->qptr != NULL` and issue an error event message warning the user about a misconfiguration, and either 

1. skip the configuration of the queue for that message (if we can establish that the app will still work without it)
2. exit the app, if its going to be too broken to function

**Comment by JimKaidyNASA** [comment]
I just realized (this cntECI_msgids.h was created for me and I was not paying attention to the order), that some commands and telemetry were switched.  It should be like this.  But I don't know if the hex values make any difference here.
![image](https://user-images.githubusercontent.com/52501916/66488862-abc26980-ea7c-11e9-936e-99965cd49667.png)

**Comment by JimKaidyNASA** [comment]
Would the renumbering like this help?
![image](https://user-images.githubusercontent.com/52501916/66489018-ec21e780-ea7c-11e9-9248-69e82aea5e22.png)

**Comment by SpaceSteve121** [comment]
If you look at the [definition of the packet header](https://github.com/thesamprice/cFE/blob/master/cfe/fsw/cfe-core/src/inc/ccsds.h#L62), you'll see that bit 12 of the `StreamId` field defines the packet type. You need to ensure that's correctly set based on the type of message you're expecting. Those 4 input message ID's are setting bit 12 to 1, which indicates the message is a command. If that's not the case for your system then you need to set it to 0.

The ordering in the file does not matter to ECI, but may be helpful for humans looking for a particular packet.

**Comment by JimKaidyNASA** [comment]
Bingo!  Understood.

**Comment by BaldBeacon** [comment]
> @BaldBeacon Please review the issue above.
> 
> What do you think about adding a check to ECI [here](https://github.com/nasa/ECI/blob/master/fsw/src/eci_app.c#L328) to catch this sort of misconfiguration? I don't think there's ever a case where that's a valid configuration, and I think you might've actually ran into this same issue before (when working with ECI, not SIL specifically).
> 
> We'd just need to check that `MsgRcv[idx].MsgStruct->qptr != NULL` and issue an error event message warning the user about a misconfiguration, and either
> 
> 1. skip the configuration of the queue for that message (if we can establish that the app will still work without it)
> 2. exit the app, if its going to be too broken to function

Following up with this comment, I think any checks to ensure valid values are being entered by the user are valuable. I'll open a corresponding issue.

@JimKaidyNASA 

> Bingo! Understood.

Can I interpret this as your issuing being solved?

**Comment by JimKaidyNASA** [comment]
A check would be great.  This was a user error obviously but I was getting help from a more experienced user who was not sure which was a command and which was telem.  I was not aware to catch the error.   Once I made the corrections that problem was resolved.  There's the bingo!  Thx.

**Comment by SpaceSteve121** [comment]
@BaldBeacon Once you've opened it, please comment here with a link to the new issue and then close this issue. Thanks!

**Comment by JimKaidyNASA** [comment]
I'm trying to get the syntax right for the validation command.  I've been running gdb to look at the contents of the message.  All I get is a cryptic invalid msg length error.  With the following from the cFS-GroundSystem/Guid, instructions, I know I am not interpreting it right.

![image](https://user-images.githubusercontent.com/52501916/67431140-afdca400-f5b1-11e9-95e9-40cb3722e1bb.png)


![image](https://user-images.githubusercontent.com/52501916/67430882-25944000-f5b1-11e9-99ae-c199338f9b14.png)

![image](https://user-images.githubusercontent.com/52501916/67430958-4c527680-f5b1-11e9-8da1-bfc3eae4af84.png)

**Comment by SpaceSteve121** [comment]
@JimKaidyNASA I don't think this question is related to the segfault which is the topic of this issue. Please do not re-use issues as it makes it hard to keep things organized. Each question/problem/suggestion need to be made in its own issue so that it can be handled independently.

Unfortunately I don't know that we have the answer to your question. I've never used the python commanding interface and don't know how it formats its commands. Perhaps try opening an issue in the repo containing table services and/or the python ground system and/or the guide you're following?

**Comment by SpaceSteve121** [comment]
@BaldBeacon I've opened the new issue for the check and will now close this issue.

**Comment by JimKaidyNASA** [comment]
Steve I've opened up a new issue in cFS.  Thx.
