### ISSUE TITLE
Add support for custom CCSDS commands through the ECI header

### ISSUE THREAD

**Issue by BaldBeacon** [nasa/ECI#43]
It's been a commonly requested internal feature to add support for custom commands as part of the ECI. Currently, the only commands supported are housekeeping and noop but these are standard across apps.

This feature shouldn't impact the performance of any other parts of the ECI and can be included as part of the eci_interface header file. The structure exposed should look like:
```
{
  uint8 function code
  struct defining message
  int function pointer
}
```
where function code is a 7 byte value to identify the command and the function pointer is a C style function pointer to the function to execute once the command is received. To reduce the boiler plate code needed to be written, we also include an extra field containing the structure to fill with command information.

More information on the CCSDS packet protocol can be found [here](https://public.ccsds.org/Pubs/133x0b1c2.pdf) under section 4.1.3.2: "Packet Secondary Header". The CFS uses only the ancillary field of the secondary packet header and the relevant portion for this issue will be 0x7F00 >> 8 defined as the function code of the command message.

**Comment by SpaceSteve121** [comment]
@BaldBeacon AFAIK, this feature has not been requested by any users of ECI. It has been proposed as potentially useful for one project (although there are alternative options available). While I think the need for this has yet to definitively identified, I agree it has potential use and so is probably worth discussing.

1. I think its worth defining the scope of the CCSDS standard that would be supported. As far as I can tell, the standard doesn't specify the existence or location of a function code as part of the Ancillary Data Field. The fact that its defined where it is seems to be an a quasi-standard spawned from the fact that the [CFE defines](https://github.com/nasa/cFE/blob/c6abd3779ea836cf63007b1f9bd4c1985d9a9519/fsw/cfe-core/src/inc/ccsds.h#L110) it a certain way by default. I think its reasonable to adopt the CFE standard because commands coming off the software bus are very likely to conform to that standard, even if other formats are used in other parts of the system, but I don't think the CCSDS standard is the correct source to cite for it. An implementation could just use the supplied macro (`CCSDS_RD_FC`) so that its automatically compatible with the standard used by the CFE in the case that any user ever customizes their packet header layout. 

1. > To reduce the boiler plate code needed to be written, we also include an extra field containing the structure to fill with command information.

    I don't follow this. Could you explain? Could we just define the function signature of these command processing functions to take a pointer to the message and pass the pointer from the software bus and/or command queue and not make another copy?

1. How do you envision these command processing functions interacting with the external code? I think its straightforward to see how they're receive the command to process, but much less clear how they're pass results in a generic and useful way, that does not require modification of the external code to implement.

**Comment by BaldBeacon** [comment]
> but I don't think the CCSDS standard is the correct source to cite for it

This is just background information that leads into how the CFS processes commands which I think was necessary to the scope of issue. I'm aware the CFS defines functions to extract the function code but I'd rather know the context independent specifics of message handling here (ie. the bits CFS uses for the function code).

> Could we just define the function signature of these command processing functions to take a pointer to the message and pass the pointer from the software bus and/or command queue and not make another copy?

I don't think I was implying making another copy of the struct. My point here was to say we are given a structure definition which should contain the message and we use that to perform standard validity checks before passing it over to the user. In every single CFS app I've seen, this logic is rewritten every time and even gets mentioned specifically in the CFS integration guide. I want to do everything in my power to omit CFS details from the function processing the messages but this would be necessary to do so.

> How do you envision these command processing functions interacting with the external code?

I think we have to go off the same idea as the message receive section and make an assumption these values are global and reachable from outside the external code. This might just be something we need to continue to live with.

**Comment by BaldBeacon** [comment]
Just to be sure we aren't duplicating features, could we have a quick conversation about what the ECI already provides and how this differs what what this issue is trying to add?

The closest alternative to a direct command interface provided by the ECI would be the ECI_Msg_t structure detailed [here](https://nasa.github.io/ECI/struct_e_c_i___msg__t.html). Notably, there's strong evidence to suggest that ECI_MsgRecv_t was intended to provide commanding functionality with the inclusion of the `qptr` variable in ECI_Msg_t. I hesitate to say that this implementation provides the full functionality of processing commands since we lose access to the function code section of the ancillary field used by the CFS and this is what prompted my vision to 'flip the script' and provide a callback function for the ECI to use once it sees a specific function code. The previous would negate the need for a command queue as commands would be process at a specific time during the ECI's life cycle (most likely before external code execution).

If we decide to separate the idea of commands from received messages, we can also make the claim that received messages -> telemetry which I think is easier to conceptually understand.

**Comment by SpaceSteve121** [comment]
> I don't think I was implying making another copy of the struct.

If the command processing definition contains a message structure, then doesn't that imply that its a copy (assuming that you're not suggesting re-writing the way the rest of the ECI message handling works)?

> My point here was to say we are given a structure definition which should contain the message and we use that to perform standard validity checks before passing it over to the user.

I think the following is probably a reasonable limitation... but it sounds like you're suggesting handling only fixed-format messages (which are able to be represented by a structure). Commands with optional/variable arguments would not be supported by this implementation, if I'm interpreting it correctly.

> I think we have to go off the same idea as the message receive section and make an assumption these values are global and reachable from outside the external code. This might just be something we need to continue to live with.

Well, but in the message receive section I think its more straightforward what the interface looks like and where the data goes. For a command, I'm not sure its so straightforward. Should the command definition include a user-defined pointer that's provided to the command processing function to do something with? If so, does that need to be added to your proposed command definition? Or is there some other way you envision a command function interacting with the external code?

Also, commands often issue events to inform operators of the results of the command. Do you have a vision for how to allow them to do that?

> Notably, there's strong evidence to suggest that ECI_MsgRecv_t was intended to provide commanding functionality with the inclusion of the qptr variable in ECI_Msg_t.

I think there's more than strong evidence... I believe the following functionality is demonstrable: ECI provides a buffer to hold incoming commands (in the case that multiple are received in a single cycle) and passes one to the external code for processing each cycle. 

That (I believe) is the extent that ECI can support commands without making assumptions about the way a command ought to be handled. The proposal above does make some (reasonable) assumptions about commands which the ECI was avoiding making.

> I hesitate to say that this implementation provides the full functionality of processing commands since we lose access to the function code section of the ancillary field used by the CFS

I'm don't believe this is true. My understanding is that the full packet (including header) is passed into the external code for processing, meaning that it has access to everything normal command processing logic would.

> The previous would negate the need for a command queue as commands would be process at a specific time during the ECI's life cycle (most likely before external code execution).

If there are any classes of commands not accommodated by a command processing implementation, then I think the queue's would need to be maintained to allow the external code to process commands which violate any assumptions made by the ECI command processing logic.

Along those lines, does there need to be a way to designate which APID's are still passed to the external code and which are handled by this logic? I can envision a case where a user might want some commands handled via the logic and some would still have to be handled in the external code.

> To reduce the boiler plate code needed to be written

It might be helpful if you can enumerate exactly what boilerplate code you envision this replacing. I think you had mentioned switch statements and length checks?

Part of what might be considered boilerplate code is the updating of command execution and rejection counters. How would the user-defined functions interact with these counters? Or maybe the ECI could use the return value of the user-provided function to update the counters?

**Comment by BaldBeacon** [comment]
> If so, does that need to be added to your proposed command definition?

See `int function pointer` above

> Also, commands often issue events to inform operators of the results of the command. Do you have a vision for how to allow them to do that?

This isn't supposed to be a 1 size fits all for commanding. If a user wants this kind of fidelity, they can just call the CFS api.

> I believe the following functionality is demonstrable: ECI provides a buffer to hold incoming commands (in the case that multiple are received in a single cycle)
> That (I believe) is the extent that ECI can support commands without making assumptions about the way a command ought to be handled. 

Of course we can't make ECI make an assumption about how commands can be handled, if that were the case we would be writing an AI. We wouldn't be making any assumptions here but rather providing a user interface to allow access to data manipulations when given commands.

> Along those lines, does there need to be a way to designate which APID's are still passed to the external code and which are handled by this logic?

There's nothing saying we have to get rid of existing functionality although I'm not sure this would be a useful feature.

> It might be helpful if you can enumerate exactly what boilerplate code you envision this replacing.

Using ci_lab as an example, this switch statement is boiler plate to the point where even the CFS developers guide mentions you should just copy and paste this switch statement https://github.com/nasa/ci_lab/blob/4275aeb2f2dc9dc025f2f93b8ce862f5a008e7b5/fsw/src/ci_lab_app.c#L263.

Within each processing function, there is more boilerplate where you verify the command length and cast the value to the message type you want https://github.com/nasa/ci_lab/blob/4275aeb2f2dc9dc025f2f93b8ce862f5a008e7b5/fsw/src/ci_lab_app.c#L361.

You also briefly mentioned variable length commands, obviously we can't write boiler plate to determine how the command should be processed as this should be left to the integrator. In the case where they want to parse the function in a special way, I think leaving pointer to the command structure as NULL would nicely indicate that they don't want the ECI to prepack the command.

>  the ECI could use the return value of the user-provided function to update the counters

This would definitely work. The return code could indicate an error state (if negative) or positive to indicate successful execution and increment the CC. I don't think this is currently possible with the current queue implementation as well.

To condense what I think are pros to this approach:
1. An easier to grasp interface for the integrator. We've already had situations where people use CMD MID's in the message receive structure and it leads ECI to declare the queue where that wasn't the intent (see #42 for a recent example and I can personally vouch from the first time I started using ECI).

2. Processing all commands before a single execution cycle. In other words, process each command as it comes in given a function provided by the integrator. I'm not sure this has ever been an issue but it seems like a gotcha that doesn't need to be there.

3. Pre-processing by function code. I can imagine a case where you have more than 1 command (like the sample app), needing to handle all this logic based on global structures and flags would be needlessly confusing.

4. Easier to explain to people already familiar with the CFS. Since we'd only be writing boiler plate for common CFS functionality, this would conform nicely to the idea that all ECI does is provide a standard interface for external code to the CFS.

5. In cases where the integrator has little need for commands (I think of the SGP4 example you put together), you can just omit the command structure completely and only get the standard NOOP and HK commands.

**Comment by SpaceSteve121** [comment]
I'm going to respond to your point and then provide some comments of my own in the next post.

> > If so, does that need to be added to your proposed command definition?
>
> See int function pointer above

My understanding was that field was a pointer to the function to be executed to process the command. I was asking if we need to pass it a pointer to a data structure in the external code for the user-provided function to modify. Otherwise its not clear to me how that function would affect any change in the external code.

> There's nothing saying we have to get rid of existing functionality although I'm not sure this would be a useful feature.

Can you expand on this? It seems if we're supporting traditional message passing as well as a new processing paradigm, there will need to be a way to define which path a message is handled by. In one case, the user must provide a data structure to receive the command and logic to process the message within the external code. For the other the user just needs to provide a processing function in their integration. To support side-by-side usage I think there needs to be a way to route the command, unless you think think that can be detected automatically.

> I think leaving pointer to the command structure as NULL would nicely indicate that they don't want the ECI to prepack the command.

I don't understand what you mean by `prepack`. Did you mean something like pre-validate? Otherwise, what packing would ECI be doing?

> An easier to grasp interface for the integrator. We've already had situations where people use CMD MID's in the message receive structure and it leads ECI to declare the queue where that wasn't the intent

As part of that issue resolution, I think we identified a check that can be done to mitigate this problem, so I expect this class of error to disappear independent of this new functionality.

From a cmd/tlm perspective, it would only be easier to grasp if they opt to use the new command processing functionality and all of their commands fit the assumptions such that they can be handled by this logic. In that way, all tlm would be defined as an input message and all commands would be defined in this processing. If that's not the case, it's still a mix of cmd/tlm input messages but now the user needs two sets of processing logic and needs to track which set of logic handles each command. I think that's actually more complex than the current setup.

> Processing all commands before a single execution cycle. In other words, process each command as it comes in given a function provided by the integrator. I'm not sure this has ever been an issue but it seems like a gotcha that doesn't need to be there.

Agreed that this relaxes a current limitation of the ECI. The reason that limitation has not been addressed until now is that it's yet to be a problem for the code integrated by ECI (mainly GNC/ACS code) which usually takes a small number of high-level commands (change mode, set target, etc).

> Pre-processing by function code. I can imagine a case where you have more than 1 command (like the sample app), needing to handle all this logic based on global structures and flags would be needlessly confusing.

I'm not sure what you mean by global structures and flags. The way to handle commands using current functionality is to pass the message to the external code, which looks at the fcncode, and decides which command it's received and how to appropriately handle it. Its not forcing the use of global data/flags in the processing of the command. Just in the receipt of the command.

I have a question about this above, but its not clear to me how this processing is going to interact with the external code except through the use of global data (consistent with the way the rest of the ECI interacts with the external code).

> Easier to explain to people already familiar with the CFS. Since we'd only be writing boiler plate for common CFS functionality, this would conform nicely to the idea that all ECI does is provide a standard interface for external code to the CFS.

Yea, this is a hard one. The main users of the ECI are people who aren't super familiar with the CFS, as its basically a way to avoid learning the CFS to the point that they would need to in order to write their own app. Of course, there's always a FSW integrator, who is usually familiar with CFS, but its unclear to me if this is actually an improvement in clarity.

**Comment by SpaceSteve121** [comment]
At the end of the day, I want to ensure that this feature 
1. Is needed
2. Integrates well with the current ECI workflow, features, and paradigms

One of the typical ECI workflows is that a separate (typically non-CFS) development team writes the business logic of an app and tests it in a domain-specific environment and then delivers that code to an integrator for implementation in CFS (via ECI). That workflow depends on the development process being as loosely coupled to the integration process as possible.

With current features, the external team develops their logic (which is usually core to the functionality of the app) and tests it in their environment (which is necessary if the logic is integral to their algorithms) and then delivers it to the FSW team for integration. As long as the code has been designed such that the logic is driven from a defined input (which can be mapped to a packet), this maps well to ECI since all the ECI is doing is moving data. Given the memory-only interface of the ECI, integration doesn't typically doesn't drive the development practices of the development team.

With this proposed functionality, its not clear how it integrates cleanly with the current separation of responsibility. I don't know that's its common that a piece of external code can operate without its core logic, which would be necessary for the proposed workflow in which the external code is developed/tested in a particular environment and then has its logic bolted-on during integration.

If that's not the case, then I think that forces the external team into an awkward position where they need to test their logic in their environment (which necessitates implementing the logic as part of their algorithms) and then remove/stub out/modify parts of it so that it can be implemented again in the ECI-specific command logic. At the best case, the implementation of the actual logic is already compatible (each command handled by a separate function, compatible function signatures, etc) and all that needs to be done is removing the calls to the logic from the external code so that the same logic can be called by the ECI command processing. In the worst case, it might be a re-write of the logic, which is going to require coordination between the two teams and a re-validation of the re-implemented logic.

I agree with the observation that the command parsing (implementation-wise), the command parsing is not all that different than the table validation, because in both cases the integrator has to provide a function pointer, however I think the key differences are that
* the table validation has well defined effects (either activate table or don't) whereas command logic can do anything, which makes it much harder to define a reasonable supported set of behavior and an interface which supports that
* parameter validation is something that can wait until the transition from a simulation environment to a FSW implementation (because it's an additional layer of validation, not a driver for the behavior of the code) whereas core app logic cannot

I'm open to additional discussion/other perspectives on this, but think that this whole feature set perhaps is moving in a direction opposed to the core and traditional usage of the ECI and have to think about if there's a way to reconcile that a bit more.
